// agents/ahab.js
// Discovery — reads campaign config, calls Vertex AI, writes ahab_output.json to GCS
// Model: gemini-2.5-flash (speed — fill the Catch array as fast as possible)
// Grounding: enabled (Google Search via Vertex AI)
//
// RAG integration:
//   BEFORE run — queries rag_store for previously discovered companies.
//                Injects as an "Excluded Companies" supplement so Ahab never
//                re-harvests leads already in the pipeline.
//   AFTER run  — bulk-upserts the full Catch array into rag_store so future
//                runs have a growing dedup corpus.

import 'dotenv/config';
import { callVertex, MODELS }                          from '../utils/vertex.js';
import { writeJSON }                                   from '../utils/gcs.js';
import { query, bulkUpsert, discoveryText,
         formatDiscoveryContext }                      from '../memory/rag.js';

// AHAB_SYSTEM — verbatim from REFERENCES.md. Do not modify.
const AHAB_SYSTEM = `[Task]: Your sole mission is RAW DATA HARVESTING of opportunities. You are the high-volume scraper at the front-end of the pipeline.
[Persona]: Ahab, the Hunter.
[Sub-Agents]:
  - Technical Harpooner: Scans listings for tech-stack keywords defined in campaign config.
  - Signal Harpooner: Scans for growth and health keywords defined in campaign config.

[Handoff_Protocol]:
- Crucial: You are the Find stage. Nemo is the Enrich stage.
- Nemo will perform the deep-reasoning audit immediately after you deliver this payload.
- Do not burn tokens on analysis. Give Nemo the maximum number of raw leads possible.
- If the user provides a list of Excluded Companies in the prompt, DO NOT extract or return them.

[Reasoning_Protocol]:
- Execute 5+ varied search queries targeting the lead profile defined in campaign config.
- Every search query MUST use site-specific operators and direct portals where applicable.

[Core_Directives]:
1. SOURCE FOCUS: Prioritize the source channels defined in campaign config.
2. FILTER COMPLIANCE: Apply all global_filters from campaign config.
3. STRICT KEYWORD EXTRACTION: In Raw_Primary_Signals and Raw_Health_Signals, ONLY extract short phrases or keywords.
4. SEARCH ITERATION LOGIC: Execute a multi-step Search Pivot. Log every unique query in Harpooner_Logs.
5. NO SUMMARIES: Do not explain your thought process in the logs.
6. Fill the Catch array until the output token limit is reached.
7. COMPANY_FILTER: If the actual hiring company name cannot be determined from the listing, DO NOT include it in the Catch array. Job board aggregators (Jobgether, Jobsora, Indeed, Glassdoor) are not companies. Skip any listing where Company_Name would be "Unknown" or a job board name.
CRITICAL OUTPUT FORMAT: Return ONLY raw JSON. No markdown. No code fences. No backticks. Structure: {"Harpooner_Logs": ["query"], "Catch": [{"Company_Name": "string", "Job_URL": "string", "Location_Status": "string", "Raw_Primary_Signals": ["string"], "Raw_Health_Signals": ["string"]}]}`;

/**
 * runAhab(campaignMessage, runId)
 *
 * @param {string} campaignMessage — target profile, tech stack signals, health signals,
 *                                   source channels, excluded companies
 * @param {string} runId           — pipeline run ID (generated by run.js)
 * @returns {Promise<object>} { Harpooner_Logs, Catch }
 */
export async function runAhab(campaignMessage, runId, { skipRag = false } = {}) {
  const bucket = process.env.GCS_BUCKET;
  if (!bucket) throw new Error('[ahab] GCS_BUCKET not set');

  console.log('\n🪝 AHAB — hunt starting...');
  console.log(`   Campaign: ${campaignMessage.slice(0, 120)}...`);

  // ── RAG: query for previously discovered companies ─────────────────────────
  let ragContext = '';
  if (skipRag) {
    console.log('   [rag] ⚡ SKIP_RAG — skipping discovery query');
  } else {
    try {
      const prior = await query(bucket, campaignMessage, {
        types:         ['discovery'],
        topK:          10,
        excludeRunId:  runId,
      });
      ragContext = formatDiscoveryContext(prior);
      if (prior.length) {
        console.log(`   [rag] 🧠 ${prior.length} previously discovered companies injected as exclusions`);
      } else {
        console.log('   [rag] 💡 first run — no prior discoveries in store');
      }
    } catch (err) {
      console.warn(`   [rag] ⚠️  query failed (non-fatal): ${err.message}`);
    }
  }

  const enrichedCampaign = campaignMessage + ragContext;

  // ── Vertex AI call ─────────────────────────────────────────────────────────
  const output = await callVertex(
    MODELS.FLASH,
    AHAB_SYSTEM,
    enrichedCampaign,
    { grounding: true }
  );

  const catchCount = output?.Catch?.length ?? 0;
  const logCount   = output?.Harpooner_Logs?.length ?? 0;
  console.log(`✅ Ahab — ${catchCount} leads in Catch, ${logCount} queries logged`);

  await writeJSON(bucket, 'ahab_output.json', output);

  // ── RAG: bulk-upsert Catch into store ──────────────────────────────────────
  if (catchCount > 0 && !skipRag) {
    try {
      console.log(`   [rag] 📝 embedding and storing ${catchCount} discoveries...`);
      const entries = (output.Catch ?? []).map(lead => ({
        type:     'discovery',
        run_id:   runId,
        text:     discoveryText(lead),
        metadata: {
          company_name: lead.Company_Name,
          job_url:      lead.Job_URL,
          location:     lead.Location_Status,
          signals:      [...(lead.Raw_Primary_Signals ?? []), ...(lead.Raw_Health_Signals ?? [])],
        },
      }));
      await bulkUpsert(bucket, entries);
    } catch (err) {
      console.warn(`   [rag] ⚠️  bulk upsert failed (non-fatal): ${err.message}`);
    }
  }

  return output;
}
