// agents/nemo.js
// Enrichment — reads ahab_output.json, enriches each lead, writes nemo_output.json + shipwrecked.json
// Model: gemini-2.5-pro (depth — single-lead diagnostic reasoning)
// Grounding: enabled (Google Search via Vertex AI)
//
// RAG integration:
//   BEFORE each lead — queries rag_store for similar enrichment profiles from
//                      prior runs. Injects as calibration context so Nemo
//                      classifies friction types consistently across runs.
//   AFTER each lead  — upserts ACTIVE enrichment profiles into rag_store so the
//                      corpus grows and future Nemo runs have more signal.

import 'dotenv/config';
import { callVertex, MODELS }                          from '../utils/vertex.js';
import { writeJSON }                                   from '../utils/gcs.js';
import { sanitizeDirectUrl, stripCitations }           from '../utils/payload.js';
import { query, upsert, enrichmentText,
         formatEnrichmentContext }                     from '../memory/rag.js';

// NEMO_SYSTEM — verbatim from REFERENCES.md. Do not modify.
const NEMO_SYSTEM = `[Task]: SINGLE-LEAD DIAGNOSTIC ENRICHMENT.
[Persona]: Nemo, the Intelligence Analyst.
[Mission]: Analyze ONE lead. Identify the friction or displacement signal. Produce a Clay-ready structured output.

[Clay_Readiness_Protocol]:
- Every claim must be sourced. No invented details.
- Direct_URL must be the company's own domain, confirmed by direct navigation. Return null if it cannot be independently verified.
- Contact_Recon must be a real person with a verifiable role.

[Target_Service_Intent_Routing]:
- Accounting: financial controllers, bookkeeping, reconciliation, QuickBooks spend signals
- GTM: RevOps, lead generation, CRM operations, marketing automation, Clay or n8n workflows

[Forensic_Dictionary]:
1. API Stutter: Data tools exist but do not talk to each other.
2. Scale Friction: Growth is outpacing data infrastructure capacity.
3. Manual Data Debt: Humans doing work that should be automated.
4. Displacement Signal: Paying a platform for something a specialist does better.

[CATALYST_STALE]: If the most recent funding event is older than 18 months from today, you MUST set status=SHIPWRECKED and reason_code=CATALYST_STALE. No exceptions. Return immediately after writing SHIPWRECKED status.

[The Divers — be concise, one sentence max per field]:
1. url_recon_notes: Confirm company direct domain. One sentence.
2. health_audit_notes: Note funding or growth signal if found. One sentence.
3. friction_notes: Name the friction category and one piece of evidence. One sentence.

[Core_Directives]:
- NO PROSE: Raw JSON only.
- CITATION_MANDATE: All string values must be plain prose only. No reference markers of any kind.
- PROOF_REQUIRED: Every technical claim MUST have a proof URL.
- CONTACT_RECON: Identify the decision-maker. Extract email pattern or LinkedIn profile.

OUTPUT CONTRACT:
{
  "Enriched_Lead": {
    "Company_Name": "string",
    "Direct_URL": "string",
    "Target_Service_Intent": "GTM | Accounting",
    "Forensic_Friction_Type": "API Stutter | Scale Friction | Manual Data Debt | Displacement Signal",
    "funding_signal": "string | null",
    "Job_Title": "string — the exact role title from the job posting",
    "Contact_Recon": { "name": "string", "title": "string", "email": "string | null", "linkedin": "string | null" },
    "The_Divers": { "url_recon_notes": "string", "health_audit_notes": "string", "friction_notes": "string" }
  },
  "Nemo_Enrich_Audit": { "status": "ACTIVE | SHIPWRECKED", "reason_code": "string | null" }
}`;

/**
 * runNemo(ahabOutput, runId)
 *
 * Processes each lead in ahabOutput.Catch sequentially.
 * ACTIVE leads → nemo_output.json
 * SHIPWRECKED leads → shipwrecked.json
 *
 * @param {object} ahabOutput — parsed ahab_output.json { Harpooner_Logs, Catch }
 * @param {string} runId      — pipeline run ID (generated by run.js)
 * @returns {Promise<{ active: object[], shipwrecked: object[] }>}
 */
export async function runNemo(ahabOutput, runId, { skipRag = false } = {}) {
  const bucket = process.env.GCS_BUCKET;
  if (!bucket) throw new Error('[nemo] GCS_BUCKET not set');

  const leads = ahabOutput?.Catch ?? [];
  if (!leads.length) throw new Error('[nemo] Ahab Catch is empty — nothing to enrich');

  console.log(`\n🔬 NEMO — enriching ${leads.length} leads sequentially...`);

  const active      = [];
  const shipwrecked = [];

  for (let i = 0; i < leads.length; i++) {
    const lead = leads[i];
    console.log(`  [${i + 1}/${leads.length}] ${lead.Company_Name}`);

    // ── RAG: query for similar prior enrichments ─────────────────────────────
    let ragContext = '';
    if (skipRag) {
      // skipping
    } else {
      try {
        const queryText = `${lead.Company_Name} ${(lead.Raw_Primary_Signals ?? []).join(' ')} ${(lead.Raw_Health_Signals ?? []).join(' ')}`;
        const similar = await query(bucket, queryText, {
          types:        ['enrichment'],
          topK:         3,
          excludeRunId: runId,
        });
        ragContext = formatEnrichmentContext(similar);
        if (similar.length) {
          console.log(`    [rag] 🧠 ${similar.length} similar enrichments retrieved`);
        }
      } catch (err) {
        console.warn(`    [rag] ⚠️  query failed (non-fatal): ${err.message}`);
      }
    }

    const userPrompt = JSON.stringify(lead, null, 2) + ragContext;

    try {
      const result = await callVertex(
        MODELS.PRO,
        NEMO_SYSTEM,
        userPrompt,
        { grounding: true }
      );

      // Sanitize Vertex redirect URLs
      if (result?.Enriched_Lead?.Direct_URL) {
        result.Enriched_Lead.Direct_URL = sanitizeDirectUrl(result.Enriched_Lead.Direct_URL);
      }

      // Strip citation artifacts from string fields
      _stripAll(result);

      if (result?.Nemo_Enrich_Audit?.status === 'SHIPWRECKED') {
        shipwrecked.push(result);
        console.log(`    ⚓ SHIPWRECKED — ${result.Nemo_Enrich_Audit.reason_code}`);
      } else {
        active.push(result);
        console.log(`    ✅ ACTIVE — ${result?.Enriched_Lead?.Forensic_Friction_Type}`);

        // ── RAG: upsert ACTIVE enrichment into store ─────────────────────────
        if (!skipRag) {
          try {
            const enrichedLead = result.Enriched_Lead;
            await upsert(bucket, {
              type:     'enrichment',
              run_id:   runId,
              text:     enrichmentText(enrichedLead),
              metadata: {
                company_name:  enrichedLead.Company_Name,
                friction_type: enrichedLead.Forensic_Friction_Type,
                service_intent: enrichedLead.Target_Service_Intent,
                friction_notes: enrichedLead?.The_Divers?.friction_notes ?? '',
                status:        'ACTIVE',
              },
            });
          } catch (err) {
            console.warn(`    [rag] ⚠️  upsert failed (non-fatal): ${err.message}`);
          }
        }
      }
    } catch (err) {
      console.error(`    ❌ failed on ${lead.Company_Name}: ${err.message}`);
    }
  }

  console.log(`\n✅ Nemo — ${active.length} active, ${shipwrecked.length} shipwrecked`);

  await writeJSON(bucket, 'nemo_output.json',   active);
  await writeJSON(bucket, 'shipwrecked.json',    shipwrecked);

  return { active, shipwrecked };
}

// Strip citation markers from all relevant string fields in a Nemo result
function _stripAll(result) {
  const lead   = result?.Enriched_Lead;
  const divers = lead?.The_Divers;
  const recon  = lead?.Contact_Recon;
  if (divers) {
    divers.url_recon_notes    = stripCitations(divers.url_recon_notes);
    divers.health_audit_notes = stripCitations(divers.health_audit_notes);
    divers.friction_notes     = stripCitations(divers.friction_notes);
  }
  if (recon) {
    recon.name  = stripCitations(recon.name);
    recon.title = stripCitations(recon.title);
  }
  if (lead?.funding_signal) lead.funding_signal = stripCitations(lead.funding_signal);
}
