// agents/neptune.js
// Synthesis — reads nemo_output.json, writes neptune_output.json
// Model: gemini-2.5-pro + responseSchema enforcement
// Grounding: disabled — Neptune synthesizes from Nemo's structured output only
//
// RAG integration:
//   BEFORE each Bite — queries rag_store for similar Bites from prior runs,
//                      filtered by matching friction type + service intent.
//                      Neptune is explicitly instructed to vary from these —
//                      no repeated openings, villains, or CTAs.
//   AFTER each Bite  — upserts the finished Bite into rag_store so the corpus
//                      grows. By run 5 Neptune has a real reference library.
//                      By run 10 every Bite is genuinely novel.

import 'dotenv/config';
import { callVertex, MODELS }                          from '../utils/vertex.js';
import { writeJSON }                                   from '../utils/gcs.js';
import { query, upsert, biteText,
         formatBiteContext }                           from '../memory/rag.js';

// NEPTUNE_SYSTEM — verbatim from REFERENCES.md. Do not modify.
const NEPTUNE_SYSTEM = `[Task]: OUTREACH SYNTHESIS.
[Persona]: Neptune, the Authority Engine.
[Mission]: Receive a structured Friction Profile from Nemo. Synthesize it into a Schwartz-style Outreach Bite. One job. One output.

[Prime_Directive]:
You are not selling. You are confirming what the prospect already knows.

The Bite operates on three Schwartz principles:
1. REFLECT before you claim. Name what they are already doing before offering anything.
2. NAME THE VILLAIN. Name the specific tool, process, or platform that is failing them.
3. OFFER THE SPECIFIC OUTCOME. The exact thing they already want, stated in operational language.

The Bite is 3-4 sentences. Opens by reflecting reality. Names the villain. Offers the specific outcome. Closes with one peer suggestion — never a generic call to action.

[The_Rule_of_One_Mandate]:
1. One Reader: intimate 1-on-1 engagement.
2. First-Person ONLY: I never We.
3. One Peer Suggestion: actionable insight based on their specific signals.

[Funding_Signal_Handling]:
- If funding_signal present: Open with it as a momentum hook. One short clause, then pivot to friction.
- If funding_signal null: Omit entirely. Lead with friction.

[Contact_Frame]:
Write to the contact's specific role, not the job posting.
- CTO or VP Engineering: frame around architecture debt and engineering overhead
- VP Revenue or CRO: frame around pipeline visibility and revenue predictability
- Head of Growth or CMO: frame around CAC efficiency and GTM velocity
- RevOps or Operations title: frame around data integrity and workflow reliability
- If title unknown: default to operational pain

[Core_Directives]:
- NO PROSE: Raw JSON only.
- BITE_CONSTRAINT: Maximum 3-4 sentences.
- DATA_STRICTNESS: Only reference what is in the input payload.
- VOICE_CONSTRAINT: Write as someone who has spent 200 hours studying GTM failure patterns from job postings and LinkedIn signals. Every observation comes from pattern recognition across hundreds of postings, not personal client work. State what you observed. Do not reference the act of observing.`;

// Neptune response schema — verbatim from REFERENCES.md
const NEPTUNE_SCHEMA = {
  type: 'object',
  required: ['Neptune_Log', 'Outreach_Bite', 'funding_signal'],
  properties: {
    Neptune_Log: {
      type: 'object',
      properties: {
        intent_recognized: { type: 'string' },
        friction_strategy: { type: 'string' },
        rule_of_one_check: { type: 'string' },
      },
    },
    Outreach_Bite:  { type: 'string' },
    funding_signal: { type: 'string', nullable: true },
  },
};

/**
 * runNeptune(nemoOutput, runId)
 *
 * Synthesizes an Outreach Bite for each ACTIVE lead from Nemo.
 * RAG context is queried before each Bite and written back after.
 *
 * @param {object[]} nemoOutput — parsed nemo_output.json (array of ACTIVE lead objects)
 * @param {string}   runId      — pipeline run ID (generated by run.js)
 * @returns {Promise<object[]>} finished leads with Outreach_Bite populated
 */
export async function runNeptune(nemoOutput, runId, { skipRag = false } = {}) {
  const bucket = process.env.GCS_BUCKET;
  if (!bucket) throw new Error('[neptune] GCS_BUCKET not set');

  const leads = Array.isArray(nemoOutput) ? nemoOutput : [];
  if (!leads.length) throw new Error('[neptune] Nemo output is empty — nothing to synthesize');

  console.log(`\n🔱 NEPTUNE — synthesizing ${leads.length} Outreach Bites...`);

  const finished = [];

  for (let i = 0; i < leads.length; i++) {
    const nemoResult = leads[i];
    const enrichedLead = nemoResult?.Enriched_Lead ?? {};
    const name = enrichedLead?.Company_Name ?? `Lead ${i + 1}`;
    console.log(`  [${i + 1}/${leads.length}] ${name}`);

    // ── RAG: query for similar prior Bites ───────────────────────────────────
    let ragContext = '';
    if (skipRag) {
      console.log('    [rag] ⚡ SKIP_RAG — Neptune writing fresh');
    } else {
      try {
        const queryText = `${enrichedLead.Forensic_Friction_Type ?? ''} ${enrichedLead.Job_Title ?? ''} ${enrichedLead.Target_Service_Intent ?? ''}`.trim();
        const similar = await query(bucket, queryText, {
          types:        ['bite'],
          topK:         3,
          excludeRunId: runId,
        });
        ragContext = formatBiteContext(similar);
        if (similar.length) {
          console.log(`    [rag] 🧠 ${similar.length} reference Bites retrieved — Neptune will vary`);
        } else {
          console.log('    [rag] 💡 no prior Bites — Neptune writing fresh');
        }
      } catch (err) {
        console.warn(`    [rag] ⚠️  query failed (non-fatal): ${err.message}`);
      }
    }

    const userPrompt = JSON.stringify({
      Friction_Profile: enrichedLead,
      Nemo_Audit:       nemoResult?.Nemo_Enrich_Audit ?? {},
    }, null, 2) + ragContext;

    try {
      const neptuneResult = await callVertex(
        MODELS.PRO,
        NEPTUNE_SYSTEM,
        userPrompt,
        { schema: NEPTUNE_SCHEMA }
      );

      const finished_lead = {
        Company_Name:           enrichedLead.Company_Name,
        Direct_URL:             enrichedLead.Direct_URL,
        Target_Service_Intent:  enrichedLead.Target_Service_Intent,
        Forensic_Friction_Type: enrichedLead.Forensic_Friction_Type,
        funding_signal:         enrichedLead.funding_signal ?? null,
        Job_Title:              enrichedLead.Job_Title,
        Contact_Recon:          enrichedLead.Contact_Recon,
        Neptune_Log:            neptuneResult.Neptune_Log,
        Outreach_Bite:          neptuneResult.Outreach_Bite,
      };

      finished.push(finished_lead);
      console.log(`    ✅ Bite — "${neptuneResult.Outreach_Bite.slice(0, 80)}..."`);

      // ── RAG: upsert finished Bite into store ─────────────────────────────
      if (!skipRag) {
        try {
          await upsert(bucket, {
            type:     'bite',
            run_id:   runId,
            text:     biteText(finished_lead),
            metadata: {
              company_name:  finished_lead.Company_Name,
              friction_type: finished_lead.Forensic_Friction_Type,
              contact_title: finished_lead.Job_Title ?? 'unknown',
              service_intent: finished_lead.Target_Service_Intent,
              outreach_bite: finished_lead.Outreach_Bite,
            },
          });
        } catch (err) {
          console.warn(`    [rag] ⚠️  upsert failed (non-fatal): ${err.message}`);
        }
      }
    } catch (err) {
      console.error(`    ❌ failed on ${name}: ${err.message}`);
    }
  }

  console.log(`\n✅ Neptune — ${finished.length} leads with Outreach_Bite`);

  await writeJSON(bucket, 'neptune_output.json', finished);
  return finished;
}
