/* ============================================================
   AI SCHOOL · Library (data)
   Curated resources for AI engineering. English only.
   No filler — every entry earns its place.

   Types: Book | Course | Video | Paper | Article | Interactive
   Tiers: fundamentals → intermediate → advanced
   ============================================================ */

var LIBRARY = {

  fundamentals: [
    /* ── Mathematics ─────────────────────────────────────── */
    { type: "Book",    title: "Mathematics for Machine Learning",                   author: "Deisenroth, Faisal, Ong",          url: "https://mml-book.github.io",                                                                            format: "HTML, PDF",     topic: "Math",              note: "Linear algebra, calculus, probability — all through the ML lens. Start here." },
    { type: "Video",   title: "Essence of Linear Algebra",                          author: "3Blue1Brown",                      url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab",                           format: "YouTube",       topic: "Math",              note: "The best visual intuition for linear algebra that exists. Watch before reading any textbook." },
    { type: "Video",   title: "Essence of Calculus",                                author: "3Blue1Brown",                      url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr",                           format: "YouTube",       topic: "Math",              note: "Builds genuine intuition for derivatives and integrals. 12 videos, each one earned." },
    { type: "Book",    title: "A Programmer's Introduction to Mathematics",          author: "Jeremy Kun",                       url: "https://pimbook.org",                                                                                   format: "HTML",          topic: "Math",              note: "Makes abstract math concrete for people who code. Genuinely different from textbooks." },
    { type: "Book",    title: "Linear Algebra Done Right",                           author: "Sheldon Axler",                    url: "https://linear.axler.net",                                                                              format: "HTML",          topic: "Math",              note: "The cleanest treatment of linear algebra. Builds intuition, not just mechanics." },
    { type: "Book",    title: "Convex Optimization",                                 author: "Boyd, Vandenberghe",               url: "https://web.stanford.edu/~boyd/cvxbook",                                                                format: "PDF",           topic: "Math",              note: "Stanford. Gradient descent and optimization — the engine behind all of ML." },
    { type: "Book",    title: "Introduction to Probability",                         author: "Grinstead, Snell",                 url: "https://math.dartmouth.edu/~prob/prob/prob.pdf",                                                         format: "PDF",           topic: "Math",              note: "Dartmouth. Clear, complete, free. The probability foundation you actually need." },
    { type: "Book",    title: "Think Stats: Probability and Statistics for Programmers", author: "Allen B. Downey",              url: "https://greenteapress.com/thinkstats/",                                                                  format: "HTML, PDF",     topic: "Math",              note: "Teaches stats through Python. No prerequisite math needed." },
    { type: "Book",    title: "Think Bayes: Bayesian Statistics Made Simple",        author: "Allen B. Downey",                  url: "https://www.greenteapress.com/thinkbayes/",                                                              format: "HTML, PDF",     topic: "Math",              note: "Bayesian thinking through code. Pairs with Phase 01 probability work." },
    { type: "Book",    title: "Bayesian Methods for Hackers",                        author: "Cameron Davidson-Pilon",           url: "https://camdavidsonpilon.github.io/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/",         format: "HTML, Jupyter", topic: "Math",              note: "Probabilistic programming in Python. Computational over analytical — the right approach." },
    { type: "Book",    title: "Mathematics for Computer Science",                    author: "Lehman, Leighton, Meyer",          url: "https://courses.csail.mit.edu/6.042/spring18/mcs.pdf",                                                   format: "PDF",           topic: "Math",              note: "MIT 6.042. Discrete math, graph theory, proofs. The CS foundation." },
    /* ── Python ───────────────────────────────────────────── */
    { type: "Book",    title: "Automate the Boring Stuff with Python",               author: "Al Sweigart",                      url: "https://automatetheboringstuff.com/3e/",                                                                  format: "HTML",          topic: "Python",            note: "A personal favourite. Files, web scraping, spreadsheets, PDFs, scheduling — all the unglamorous stuff you actually need." },
    { type: "Book",    title: "Beyond the Basic Stuff with Python",                  author: "Al Sweigart",                      url: "https://inventwithpython.com/beyond/",                                                                    format: "HTML",          topic: "Python",            note: "Picks up where Automate leaves off. Code style, OOP, debugging, performance." },
    { type: "Book",    title: "A Whirlwind Tour of Python",                          author: "Jake VanderPlas",                  url: "https://jakevdp.github.io/WhirlwindTourOfPython/",                                                       format: "HTML, Jupyter", topic: "Python",            note: "The fastest Python ramp-up that exists. Read this before Phase 01." },
    { type: "Book",    title: "Python Data Science Handbook",                        author: "Jake VanderPlas",                  url: "https://jakevdp.github.io/PythonDataScienceHandbook",                                                    format: "HTML, Jupyter", topic: "Python",            note: "NumPy, Pandas, Matplotlib, Scikit-learn — the scientific Python stack in one book." },
    { type: "Book",    title: "The Hitchhiker's Guide to Python",                    author: "Kenneth Reitz, Tanya Schlusser",   url: "https://docs.python-guide.org",                                                                         format: "HTML",          topic: "Python",            note: "Best practices, tooling, project structure. Opinionated and correct." },
    { type: "Book",    title: "Architecture Patterns with Python",                   author: "Harry Percival, Bob Gregory",      url: "https://www.cosmicpython.com/book/preface.html",                                                         format: "HTML",          topic: "Python",            note: "Domain-driven design, clean architecture, TDD — applied to Python services." },
    { type: "Book",    title: "Python Programming and Numerical Methods",            author: "Kong, Siauw, Bayen",               url: "https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html",                                       format: "HTML, Jupyter", topic: "Python",            note: "Berkeley. Scientific Python for engineers. Bridges math and code." },
    { type: "Book",    title: "Research Software Engineering with Python",           author: "Irving, Hertweck, Johnston, et al.", url: "https://merely-useful.tech/py-rse/",                                                                   format: "HTML",          topic: "Python",            note: "How to write Python that lasts: testing, packaging, Git, reproducibility." },
    /* ── Algorithms ───────────────────────────────────────── */
    { type: "Book",    title: "Algorithms",                                          author: "Jeff Erickson",                    url: "https://jeffe.cs.illinois.edu/teaching/algorithms/book/Algorithms-JeffE.pdf",                            format: "PDF",           topic: "Algorithms",        note: "Illinois. The best free algorithms textbook. Rigorous and readable." },
    { type: "Book",    title: "Algorithms, 4th Edition",                             author: "Sedgewick, Wayne",                 url: "https://algs4.cs.princeton.edu/home/",                                                                  format: "HTML",          topic: "Algorithms",        note: "Princeton. Data structures and algorithms implemented clearly." },
    { type: "Book",    title: "Foundations of Computer Science",                     author: "Aho, Ullman",                      url: "http://infolab.stanford.edu/~ullman/focs.html",                                                          format: "HTML",          topic: "Algorithms",        note: "Stanford. Automata, languages, complexity — the theoretical backbone." }
  ],

  intermediate: [
    /* ── Andrew Ng ────────────────────────────────────────── */
    { type: "Course",  title: "Machine Learning Specialization",                     author: "Andrew Ng (DeepLearning.AI)",      url: "https://www.coursera.org/specializations/machine-learning-introduction",                                  format: "Video, Jupyter", topic: "Machine Learning", note: "The course that got a million people into ML. Modernised with Python and NumPy. Audit free." },
    { type: "Course",  title: "Deep Learning Specialization",                        author: "Andrew Ng (DeepLearning.AI)",      url: "https://www.coursera.org/specializations/deep-learning",                                                 format: "Video, Jupyter", topic: "Deep Learning",    note: "5 courses: backprop, CNNs, sequence models, transformers, RLHF basics. Audit free. Phase 03-07 companion." },
    { type: "Course",  title: "Machine Learning Engineering for Production (MLOps)", author: "Andrew Ng (DeepLearning.AI)",      url: "https://www.coursera.org/specializations/machine-learning-engineering-for-production-mlops",               format: "Video, Jupyter", topic: "MLOps",            note: "4 courses covering the full production ML lifecycle. Required reading for Phase 17." },
    { type: "Course",  title: "Natural Language Processing Specialization",          author: "DeepLearning.AI",                  url: "https://www.coursera.org/specializations/natural-language-processing",                                    format: "Video, Jupyter", topic: "NLP",              note: "4 courses: classification, seq2seq, trees, attention. Bridges Phase 05 and 07." },
    /* ── Machine Learning ─────────────────────────────────── */
    { type: "Book",    title: "An Introduction to Statistical Learning",             author: "James, Witten, Hastie, Tibshirani", url: "https://www.statlearning.com",                                                                         format: "PDF",           topic: "Machine Learning",  note: "The applied ML textbook. Python edition available. Start here before Phase 02." },
    { type: "Book",    title: "The Elements of Statistical Learning",                author: "Hastie, Tibshirani, Friedman",     url: "https://web.stanford.edu/~hastie/ElemStatLearn/",                                                        format: "PDF",           topic: "Machine Learning",  note: "Stanford. The rigorous version of ISLR. Reference for the math behind the methods." },
    { type: "Book",    title: "Understanding Machine Learning: From Theory to Algorithms", author: "Shalev-Shwartz, Ben-David",  url: "https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning",                                         format: "PDF",           topic: "Machine Learning",  note: "Theory-first. If you want to understand WHY algorithms work, not just how to use them." },
    { type: "Book",    title: "Machine Learning from Scratch",                       author: "Danny Friedman",                   url: "https://dafriedman97.github.io/mlbook/",                                                                 format: "HTML, PDF",     topic: "Machine Learning",  note: "Builds every algorithm from math, then code. Mirrors the curriculum's Build It approach." },
    { type: "Book",    title: "Interpretable Machine Learning",                      author: "Christoph Molnar",                 url: "https://christophm.github.io/interpretable-ml-book/",                                                    format: "HTML",          topic: "Machine Learning",  note: "SHAP, LIME, feature importance, model inspection. Essential for production ML." },
    { type: "Article", title: "The Bitter Lesson",                                   author: "Rich Sutton",                      url: "http://www.incompleteideas.net/IncIdeas/BitterLesson.html",                                               format: "HTML",          topic: "Machine Learning",  note: "The most important essay in ML. Scale beats hand-crafted induction every time. Read it." },
    { type: "Book",    title: "Patterns, Predictions, and Actions",                  author: "Hardt, Recht",                     url: "https://mlstory.org/pdf/patterns.pdf",                                                                   format: "PDF",           topic: "Machine Learning",  note: "ML through the lens of decision-making and causality. A different, important angle." },
    /* ── Deep Learning ────────────────────────────────────── */
    { type: "Video",   title: "Neural Networks: Zero to Hero",                       author: "Andrej Karpathy",                  url: "https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ",                           format: "YouTube",       topic: "Deep Learning",     note: "Builds micrograd, makemore, and nanoGPT from scratch. The best from-scratch series that exists." },
    { type: "Video",   title: "But what is a neural network?",                       author: "3Blue1Brown",                      url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi",                           format: "YouTube",       topic: "Deep Learning",     note: "4-video series. Visual intuition for how neural networks learn. Watch before Phase 03." },
    { type: "Course",  title: "MIT 6.S191: Introduction to Deep Learning",           author: "MIT",                              url: "https://introtodeeplearning.com",                                                                        format: "Video, Slides", topic: "Deep Learning",     note: "MIT's annual deep learning course. Current, free, lab exercises included. Strong Phase 03 companion." },
    { type: "Course",  title: "Practical Deep Learning for Coders",                  author: "Jeremy Howard, fast.ai",           url: "https://course.fast.ai",                                                                                format: "Video, Jupyter", topic: "Deep Learning",    note: "Top-down, application-first. Best way to build things fast while learning the theory." },
    { type: "Book",    title: "Deep Learning",                                       author: "Goodfellow, Bengio, Courville",    url: "https://www.deeplearningbook.org",                                                                       format: "HTML",          topic: "Deep Learning",     note: "The canonical deep learning textbook. Read alongside Phases 03-07." },
    { type: "Book",    title: "Dive into Deep Learning",                             author: "Zhang, Lipton, Li, Smola",         url: "https://d2l.ai",                                                                                        format: "HTML, Jupyter", topic: "Deep Learning",     note: "Interactive, multi-framework, updated constantly. The practical counterpart to Goodfellow." },
    { type: "Book",    title: "Neural Networks and Deep Learning",                   author: "Michael Nielsen",                  url: "http://neuralnetworksanddeeplearning.com",                                                                format: "HTML",          topic: "Deep Learning",     note: "Best intro to neural networks that exists. Builds intuition from backprop up." },
    { type: "Book",    title: "The Little Book of Deep Learning",                    author: "Francois Fleuret",                 url: "https://fleuret.org/public/lbdl.pdf",                                                                    format: "PDF",           topic: "Deep Learning",     note: "Dense, precise, free. EPFL. 200 pages that cover everything essential." },
    { type: "Book",    title: "Deep Learning for Coders with fastai and PyTorch",    author: "Jeremy Howard, Sylvain Gugger",    url: "https://fastbook.fast.ai",                                                                              format: "Jupyter",       topic: "Deep Learning",     note: "The companion book to fast.ai's course. Chapter-by-chapter implementation exercises." },
    /* ── Transformers ────────────────────────────────────── */
    { type: "Paper",   title: "Attention Is All You Need",                           author: "Vaswani et al.",                   url: "https://arxiv.org/abs/1706.03762",                                                                       format: "PDF",           topic: "Transformers",      note: "The transformer paper. Required reading before Phase 07. Remarkably readable." },
    { type: "Article", title: "The Illustrated Transformer",                         author: "Jay Alammar",                      url: "https://jalammar.github.io/illustrated-transformer/",                                                    format: "HTML",          topic: "Transformers",      note: "The clearest visual explanation of self-attention and transformers. Read before the paper." },
    { type: "Article", title: "Understanding LSTMs",                                 author: "Christopher Olah",                 url: "https://colah.github.io/posts/2015-08-Understanding-LSTMs/",                                            format: "HTML",          topic: "Transformers",      note: "The definitive explanation of LSTMs. Still essential context for understanding attention." },
    { type: "Interactive", title: "The Annotated Transformer",                       author: "Harvard NLP",                      url: "https://nlp.seas.harvard.edu/annotated-transformer/",                                                    format: "Jupyter",       topic: "Transformers",      note: "The transformer paper with inline code annotations. Build it line by line." },
    /* ── Computer Vision ──────────────────────────────────── */
    { type: "Book",    title: "Computer Vision: Algorithms and Applications",        author: "Richard Szeliski",                 url: "https://szeliski.org/Book/",                                                                            format: "PDF, HTML",     topic: "Computer Vision",   note: "The definitive CV reference. Read alongside Phase 04." },
    { type: "Book",    title: "Programming Computer Vision with Python",             author: "Jan Erik Solem",                   url: "http://programmingcomputervision.com",                                                                    format: "PDF",           topic: "Computer Vision",   note: "Hands-on CV with Python. Feature detection, segmentation, reconstruction." },
    /* ── NLP ──────────────────────────────────────────────── */
    { type: "Book",    title: "Speech and Language Processing (3rd ed. draft)",      author: "Jurafsky, Martin",                 url: "https://web.stanford.edu/~jurafsky/slp3/ed3book.pdf",                                                    format: "PDF",           topic: "NLP",               note: "Stanford. The NLP bible. Covers transformers, LLMs, parsing, semantics. Read Phase 05-07." },
    { type: "Book",    title: "Natural Language Processing with Python",             author: "Bird, Klein, Loper",               url: "http://www.nltk.org/book/",                                                                              format: "HTML",          topic: "NLP",               note: "NLTK book. Classic NLP foundations with Python. Good companion to Phase 05." },
    { type: "Video",   title: "Stanford CS224N: NLP with Deep Learning",             author: "Christopher Manning",              url: "https://www.youtube.com/playlist?list=PLoROMvodv4rOSH4v6133s9LFPRHjEmbmJ",                           format: "YouTube",       topic: "NLP",               note: "Stanford. The gold standard NLP lecture series. Transformers, BERT, GPT from first principles." },
    /* ── Reinforcement Learning ───────────────────────────── */
    { type: "Book",    title: "Reinforcement Learning: An Introduction",             author: "Sutton, Barto",                    url: "http://incompleteideas.net/book/RLbook2020.pdf",                                                          format: "PDF",           topic: "Reinforcement Learning", note: "The RL textbook. No substitute. Read alongside Phase 09." },
    { type: "Video",   title: "RL Course by David Silver",                           author: "David Silver (DeepMind)",          url: "https://www.youtube.com/playlist?list=PLqYmG7hTraZDM-OYHWgPebj2MfCFzFObQ",                           format: "YouTube",       topic: "Reinforcement Learning", note: "10 lectures. The clearest free RL course. Builds from MDPs to AlphaGo. Phase 09 companion." },
    { type: "Book",    title: "Algorithms for Reinforcement Learning",               author: "Csaba Szepesvari",                 url: "https://sites.ualberta.ca/~szepesva/papers/RLAlgsInMDPs.pdf",                                           format: "PDF",           topic: "Reinforcement Learning", note: "Concise, mathematical treatment of RL algorithms. Companion to Sutton & Barto." },
    /* ── Data Science ─────────────────────────────────────── */
    { type: "Book",    title: "Python for Data Analysis",                            author: "Wes McKinney",                     url: "https://wesmckinney.com/book/",                                                                          format: "HTML",          topic: "Data Science",      note: "Written by the creator of Pandas. The authoritative reference." },
    { type: "Book",    title: "Mining of Massive Datasets",                          author: "Leskovec, Rajaraman, Ullman",      url: "http://infolab.stanford.edu/~ullman/mmds/book.pdf",                                                       format: "PDF",           topic: "Data Science",      note: "Stanford. MapReduce, similarity, clustering, recommendations at scale." },
    { type: "Book",    title: "Data Science at the Command Line",                    author: "Jeroen Janssens",                  url: "https://datascienceatthecommandline.com/2e/",                                                            format: "HTML",          topic: "Data Science",      note: "Shell tools for data pipelines. Underrated skill for any ML engineer." },
    /* ── Julia ────────────────────────────────────────────── */
    { type: "Book",    title: "Julia Data Science",                                  author: "Storopoli, Huijzer, Alonso",       url: "https://juliadatascience.io",                                                                            format: "HTML",          topic: "Julia",             note: "Data science in Julia from scratch. Pairs with the Julia lessons in Phases 01-02." },
    { type: "Book",    title: "Think Julia",                                         author: "Ben Lauwens, Allen Downey",        url: "https://benlauwens.github.io/ThinkJulia.jl/latest/book.html",                                            format: "HTML",          topic: "Julia",             note: "Best Julia intro. Clear, practical, builds real intuition." },
    { type: "Book",    title: "Quantitative Economics with Julia",                   author: "Perla, Sargent, Stachurski",       url: "https://julia.quantecon.org",                                                                            format: "HTML",          topic: "Julia",             note: "Scientific computing with Julia. Numerical methods, optimization, dynamics." }
  ],

  advanced: [
    /* ── LLMs ─────────────────────────────────────────────── */
    { type: "Article", title: "The Illustrated GPT-2",                               author: "Jay Alammar",                      url: "https://jalammar.github.io/illustrated-gpt2/",                                                           format: "HTML",          topic: "LLMs",              note: "Walks through GPT-2 inference token by token, visually. The best LLM internals explainer." },
    { type: "Course",  title: "Hugging Face LLM Course",                             author: "Hugging Face",                     url: "https://huggingface.co/learn/llm-course/en/chapter1/1",                                                  format: "HTML",          topic: "LLMs",              note: "End-to-end LLM engineering: pretraining, fine-tuning, RLHF, deployment. Current." },
    { type: "Book",    title: "LLM Engineer's Handbook",                             author: "Maxime Labonne, Paul Iusztin",     url: "https://github.com/PacktPublishing/LLM-Engineers-Handbook",                                             format: "Jupyter",       topic: "LLMs",              note: "Full production LLM pipeline: dataset creation, fine-tuning, RAG, inference, deployment. Phase 11." },
    { type: "Paper",   title: "Training language models to follow instructions (InstructGPT)", author: "Ouyang et al. (OpenAI)", url: "https://arxiv.org/abs/2203.02155",                                                                       format: "PDF",           topic: "LLMs",              note: "The RLHF paper that changed everything. Foundation of every chat model. Phase 11 essential." },
    { type: "Paper",   title: "Scaling Laws for Neural Language Models",             author: "Kaplan et al. (OpenAI)",           url: "https://arxiv.org/abs/2001.08361",                                                                       format: "PDF",           topic: "LLMs",              note: "How loss scales with compute, data, and parameters. The Chinchilla precursor. Phase 10." },
    { type: "Paper",   title: "Training Compute-Optimal Large Language Models (Chinchilla)", author: "Hoffmann et al. (DeepMind)", url: "https://arxiv.org/abs/2203.15556",                                                                    format: "PDF",           topic: "LLMs",              note: "Chinchilla. Optimal token-to-parameter ratio. Changed how every lab trains models." },
    { type: "Book",    title: "Probabilistic Machine Learning: Advanced Topics",     author: "Kevin Murphy",                     url: "https://probml.github.io/pml-book/book2.html",                                                           format: "PDF",           topic: "LLMs",              note: "State space models, diffusion, flows, transformers — the mathematical frontier." },
    /* ── Fine-tuning & Alignment ──────────────────────────── */
    { type: "Paper",   title: "LoRA: Low-Rank Adaptation of Large Language Models", author: "Hu et al. (Microsoft)",            url: "https://arxiv.org/abs/2106.09685",                                                                       format: "PDF",           topic: "Fine-tuning",       note: "The fine-tuning technique now used everywhere. 20 pages, changes everything about how you adapt models." },
    { type: "Paper",   title: "Constitutional AI: Harmlessness from AI Feedback",   author: "Bai et al. (Anthropic)",           url: "https://arxiv.org/abs/2212.08073",                                                                       format: "PDF",           topic: "Safety",            note: "How Anthropic built Claude's safety. RLHF without human harm labels. Phase 18 essential." },
    { type: "Article", title: "Extrinsic Hallucinations in LLMs",                   author: "Lilian Weng",                      url: "https://lilianweng.github.io/posts/2024-07-07-hallucination/",                                           format: "HTML",          topic: "Safety",            note: "Taxonomy, causes, and mitigations for hallucination. Weng's blog is the best technical writing in AI." },
    /* ── Agents ───────────────────────────────────────────── */
    { type: "Article", title: "LLM Powered Autonomous Agents",                       author: "Lilian Weng",                      url: "https://lilianweng.github.io/posts/2023-06-23-agent/",                                                   format: "HTML",          topic: "Agents",            note: "The definitive survey of LLM agent architecture: planning, memory, tool use. Phase 14 foundation." },
    { type: "Book",    title: "Artificial Intelligence: Foundations of Computational Agents", author: "Poole, Mackworth",        url: "https://artint.info",                                                                                   format: "HTML",          topic: "Agents",            note: "Cambridge. Comprehensive agent theory — planning, search, learning, reasoning." },
    { type: "Book",    title: "How to Build Optimal AI Agents",                      author: "Tiago Monteiro",                   url: "https://www.freecodecamp.org/news/how-to-build-optimal-ai-agents-that-actually-work-a-handbook-for-devs/", format: "HTML",        topic: "Agents",            note: "Practical handbook for production agent systems. Pairs with Phases 13-16." },
    /* ── Generative AI ────────────────────────────────────── */
    { type: "Article", title: "What are Diffusion Models?",                          author: "Lilian Weng",                      url: "https://lilianweng.github.io/posts/2021-07-11-diffusion-models/",                                        format: "HTML",          topic: "Generative AI",     note: "The clearest explanation of DDPM, score matching, and the math behind Stable Diffusion." },
    { type: "Book",    title: "Graph Representational Learning",                     author: "William Hamilton",                 url: "https://www.cs.mcgill.ca/~wlh/grl_book/",                                                                format: "PDF",           topic: "Generative AI",     note: "McGill. GNNs, knowledge graphs, graph transformers. Increasingly central to generative models." },
    /* ── Production & Infrastructure ─────────────────────── */
    { type: "Paper",   title: "FlashAttention: Fast and Memory-Efficient Exact Attention", author: "Dao et al. (Stanford)",     url: "https://arxiv.org/abs/2205.14135",                                                                       format: "PDF",           topic: "MLOps",             note: "How modern transformers actually run fast. IO-aware attention, tiling. Phase 17 context." },
    { type: "Book",    title: "Practitioners Guide to MLOps",                        author: "Google Cloud",                     url: "https://services.google.com/fh/files/misc/practitioners_guide_to_mlops_whitepaper.pdf",                   format: "PDF",           topic: "MLOps",             note: "Google. The production ML lifecycle: data, training, evaluation, deployment, monitoring." },
    { type: "Book",    title: "Introduction to Machine Learning Systems",            author: "Vijay Janapa Reddi",               url: "https://www.mlsysbook.ai/assets/downloads/Machine-Learning-Systems.pdf",                                  format: "PDF",           topic: "MLOps",             note: "Hardware-aware ML: efficiency, deployment, edge, quantization. Phase 17 prerequisite." },
    { type: "Book",    title: "Is Parallel Programming Hard?",                       author: "Paul McKenney",                    url: "https://www.kernel.org/pub/linux/kernel/people/paulmck/perfbook/perfbook.html",                            format: "HTML, PDF",     topic: "MLOps",             note: "The definitive guide to concurrent systems. Memory models, locking, RCU — for serious infra." },
    /* ── Rust ─────────────────────────────────────────────── */
    { type: "Book",    title: "The Rust Programming Language",                       author: "Klabnik, Nichols, et al.",         url: "https://doc.rust-lang.org/book",                                                                        format: "HTML",          topic: "Rust",              note: "The official Rust book. Best language documentation that exists. Start here." },
    { type: "Book",    title: "Rust by Example",                                     author: "Rust community",                   url: "https://doc.rust-lang.org/stable/rust-by-example",                                                       format: "HTML",          topic: "Rust",              note: "Learn by reading and running examples. Companion to the Book." },
    { type: "Book",    title: "Rust Atomics and Locks",                              author: "Mara Bos",                         url: "https://marabos.nl/atomics",                                                                             format: "HTML",          topic: "Rust",              note: "Concurrency in Rust: atomics, mutexes, channels, memory ordering. For systems work." },
    { type: "Book",    title: "Effective Rust",                                      author: "David Drysdale",                   url: "https://www.lurklurk.org/effective-rust",                                                                format: "HTML, PDF",     topic: "Rust",              note: "35 specific ways to write better Rust. Bridges beginner and expert usage." },
    { type: "Book",    title: "High Assurance Rust",                                 author: "Tiemoko Ballo",                    url: "https://highassurance.rs",                                                                               format: "HTML",          topic: "Rust",              note: "Rust for safety-critical systems. Embedded, verification, formal methods." },
    /* ── TypeScript ───────────────────────────────────────── */
    { type: "Book",    title: "TypeScript Deep Dive",                                author: "Basarat Ali Syed",                 url: "https://basarat.gitbooks.io/typescript/",                                                                format: "HTML",          topic: "TypeScript",        note: "The most complete TypeScript reference. Battle-tested by thousands." },
    { type: "Book",    title: "Total TypeScript Essentials",                         author: "Matt Pocock",                      url: "https://www.totaltypescript.com/books/total-typescript-essentials",                                       format: "HTML",          topic: "TypeScript",        note: "Modern TypeScript patterns: generics, type transformations, inference. Current." },
    { type: "Book",    title: "TypeScript Handbook",                                 author: "Microsoft",                        url: "https://www.typescriptlang.org/docs/handbook/intro.html",                                                format: "HTML",          topic: "TypeScript",        note: "The official reference. Dry but authoritative. Keep as a lookup." },
    /* ── Prompt Engineering ───────────────────────────────── */
    { type: "Book",    title: "Prompt Engineering Guide",                            author: "DAIR.AI",                          url: "https://www.promptingguide.ai",                                                                         format: "HTML",          topic: "Prompt Engineering", note: "Comprehensive, maintained, free. Chain-of-thought, RAG, agents, safety." },
    /* ── Professional ─────────────────────────────────────── */
    { type: "Book",    title: "Software Engineering at Google",                      author: "Winters, Manshreck, Wright",       url: "https://abseil.io/resources/swe-book",                                                                  format: "HTML",          topic: "Professional",      note: "How Google builds software at scale. Testing, reviews, deprecation, culture." },
    { type: "Paper",   title: "A Selective Overview of Deep Learning",               author: "Fan, Ma, Zhong",                   url: "https://arxiv.org/abs/1904.05526",                                                                       format: "PDF",           topic: "Research",          note: "Princeton. Statistical theory behind deep learning. For understanding convergence and generalization." }
  ]
};
